export const userConstants = {
  USER_REGISTER_REQUEST: `USER_REGISTER_REQUEST`,
  USER_REGISTER_SUCCESS: `USER_REGISTER_SUCCESS`,
  USER_REGISTER_FAIL: `USER_REGISTER_FAIL`,
  USER_REGISTER_RESET: `USER_REGISTER_RESET`,

  USER_LOGIN_REQUEST: `USER_LOGIN_REQUEST`,
  USER_LOGIN_SUCCESS: `USER_LOGIN_SUCCESS`,
  USER_LOGIN_FAIL: `USER_LOGIN_FAIL`,
  USER_LOGOUT: `USER_LOGOUT`,

  SET_ERROR_TO_NULL: `SET_ERROR_TO_NULL`,
};

export const goalConstants = {
  ADD_SHORT_TERM_GOAL_REQUEST: `ADD_SHORT_TERM_GOAL_REQUEST`,
  ADD_SHORT_TERM_GOAL_SUCCESS: `ADD_SHORT_TERM_GOAL_SUCCESS`,
  ADD_SHORT_TERM_GOAL_FAIL: `ADD_SHORT_TERM_GOAL_FAIL`,
};
