/* eslint-disable no-dupe-keys */
export const userConstants = {
  USER_REGISTER_REQUEST: `USER_REGISTER_REQUEST`,
  USER_REGISTER_SUCCESS: `USER_REGISTER_SUCCESS`,
  USER_REGISTER_FAIL: `USER_REGISTER_FAIL`,
  USER_REGISTER_RESET: `USER_REGISTER_RESET`,

  USER_LOGIN_REQUEST: `USER_LOGIN_REQUEST`,
  USER_LOGIN_SUCCESS: `USER_LOGIN_SUCCESS`,
  USER_LOGIN_FAIL: `USER_LOGIN_FAIL`,
  USER_LOGOUT: `USER_LOGOUT`,

  SET_ERROR_TO_NULL: `SET_ERROR_TO_NULL`,
};

export const shortTermGoalsConstants = {
  ADD_SHORT_TERM_GOAL_REQUEST: `ADD_SHORT_TERM_GOAL_REQUEST`,
  ADD_SHORT_TERM_GOAL_SUCCESS: `ADD_SHORT_TERM_GOAL_SUCCESS`,
  ADD_SHORT_TERM_GOAL_FAIL: `ADD_SHORT_TERM_GOAL_FAIL`,

  REMOVE_SHORT_TERM_GOAL_REQUEST: `REMOVE_SHORT_TERM_GOAL_REQUEST`,
  REMOVE_SHORT_TERM_GOAL_SUCCESS: `REMOVE_SHORT_TERM_GOAL_SUCCESS`,
  REMOVE_SHORT_TERM_GOAL_FAIL: `REMOVE_SHORT_TERM_GOAL_FAIL`,

  SHORT_TERM_GOALS_LIST_REQUEST: `SHORT_TERM_GOALS_LIST_REQUEST`,
  SHORT_TERM_GOALS_LIST_SUCCESS: `SHORT_TERM_GOALS_LIST_SUCCESS`,
  SHORT_TERM_GOALS_LIST_FAIL: `SHORT_TERM_GOALS_LIST_FAIL`,

  GET_TOTAL_SHORT_TERM_GOALS_REQUEST: `GET_TOTAL_SHORT_TERM_GOALS_REQUEST`,
  GET_TOTAL_SHORT_TERM_GOALS_SUCCESS: `GET_TOTAL_SHORT_TERM_GOALS_SUCCESS`,
  GET_TOTAL_SHORT_TERM_GOALS_FAIL: `GET_TOTAL_SHORT_TERM_GOALS_FAIL`,
};

export const longTermGoalsConstants = {
  ADD_LONG_TERM_GOAL_REQUEST: `ADD_LONG_TERM_GOAL_REQUEST`,
  ADD_LONG_TERM_GOAL_SUCCESS: `ADD_LONG_TERM_GOAL_SUCCESS`,
  ADD_LONG_TERM_GOAL_FAIL: `ADD_LONG_TERM_GOAL_FAIL`,

  REMOVE_LONG_TERM_GOAL_REQUEST: `REMOVE_LONG_TERM_GOAL_REQUEST`,
  REMOVE_LONG_TERM_GOAL_SUCCESS: `REMOVE_LONG_TERM_GOAL_SUCCESS`,
  REMOVE_LONG_TERM_GOAL_FAIL: `REMOVE_LONG_TERM_GOAL_FAIL`,

  LONG_TERM_GOALS_LIST_REQUEST: `LONG_TERM_GOALS_LIST_REQUEST`,
  LONG_TERM_GOALS_LIST_SUCCESS: `LONG_TERM_GOALS_LIST_SUCCESS`,
  LONG_TERM_GOALS_LIST_FAIL: `LONG_TERM_GOALS_LIST_FAIL`,

  GET_TOTAL_LONG_TERM_GOALS_REQUEST: `GET_TOTAL_LONG_TERM_GOALS_REQUEST`,
  GET_TOTAL_LONG_TERM_GOALS_SUCCESS: `GET_TOTAL_LONG_TERM_GOALS_SUCCESS`,
  GET_TOTAL_LONG_TERM_GOALS_FAIL: `GET_TOTAL_LONG_TERM_GOALS_FAIL`,
};

export const achievementConstants = {
  CREATE_ACHIEVEMENT_REQUEST: `CREATE_ACHIEVEMENT_REQUEST`,
  CREATE_ACHIEVEMENT_SUCCESS: `CREATE_ACHIEVEMENT_SUCCESS`,
  CREATE_ACHIEVEMENT_FAIL: `CREATE_ACHIEVEMENT_FAIL`,

  GET_ACHIEVEMENTS_REQUEST: `GET_ACHIEVEMENTS_REQUEST`,
  GET_ACHIEVEMENTS_SUCCESS: `GET_ACHIEVEMENTS_SUCCESS`,
  GET_ACHIEVEMENTS_FAIL: `GET_ACHIEVEMENTS_FAIL`,

  REMOVE_ACHIEVEMENT_REQUEST: `REMOVE_ACHIEVEMENT_REQUEST`,
  REMOVE_ACHIEVEMENT_SUCCESS: `REMOVE_ACHIEVEMENT_SUCCESS`,
  REMOVE_ACHIEVEMENT_FAIL: `REMOVE_ACHIEVEMENT_FAIL`,

  GET_TOTAL_ACHIEVEMENTS_REQUEST: `GET_TOTAL_ACHIEVEMENTS_REQUEST`,
  GET_TOTAL_ACHIEVEMENTS_SUCCESS: `GET_TOTAL_ACHIEVEMENTS_SUCCESS`,
  GET_TOTAL_ACHIEVEMENTS_FAIL: `GET_TOTAL_ACHIEVEMENTS_FAIL`,
};
export const improvementsConstants = {
  CREATE_IMPROVEMENT_REQUEST: `CREATE_IMPROVEMENT_REQUEST`,
  CREATE_IMPROVEMENT_SUCCESS: `CREATE_IMPROVEMENT_SUCCESS`,
  CREATE_IMPROVEMENT_FAIL: `CREATE_IMPROVEMENT_FAIL`,

  GET_IMPROVEMENTS_REQUEST: `GET_IMPROVEMENTS_REQUEST`,
  GET_IMPROVEMENTS_SUCCESS: `GET_IMPROVEMENTS_SUCCESS`,
  GET_IMPROVEMENTS_FAIL: `GET_IMPROVEMENTS_FAIL`,

  REMOVE_IMPROVEMENT_REQUEST: `REMOVE_IMPROVEMENT_REQUEST`,
  REMOVE_IMPROVEMENT_SUCCESS: `REMOVE_IMPROVEMENT_SUCCESS`,
  REMOVE_IMPROVEMENT_FAIL: `REMOVE_IMPROVEMENT_FAIL`,

  GET_TOTAL_IMPROVEMENTS_REQUEST: `GET_TOTAL_IMPROVEMENTS_REQUEST`,
  GET_TOTAL_IMPROVEMENTS_SUCCESS: `GET_TOTAL_IMPROVEMENTS_SUCCESS`,
  GET_TOTAL_IMPROVEMENTS_FAIL: `GET_TOTAL_IMPROVEMENTS_FAIL`,
};

export const mistakesConstants = {
  CREATE_MISTAKE_REQUEST: `CREATE_MISTAKE_REQUEST`,
  CREATE_MISTAKE_SUCCESS: `CREATE_MISTAKE_SUCCESS`,
  CREATE_MISTAKE_FAIL: `CREATE_MISTAKE_FAIL`,

  GET_MISTAKES_REQUEST: `GET_MISTAKES_REQUEST`,
  GET_MISTAKES_SUCCESS: `GET_MISTAKES_SUCCESS`,
  GET_MISTAKES_FAIL: `GET_MISTAKES_FAIL`,

  REMOVE_MISTAKE_REQUEST: `REMOVE_MISTAKE_REQUEST`,
  REMOVE_MISTAKE_SUCCESS: `REMOVE_MISTAKE_SUCCESS`,
  REMOVE_MISTAKE_FAIL: `REMOVE_MISTAKE_FAIL`,

  GET_TOTAL_MISTAKES_REQUEST: `GET_TOTAL_MISTAKES_REQUEST`,
  GET_TOTAL_MISTAKES_SUCCESS: `GET_TOTAL_MISTAKES_SUCCESS`,
  GET_TOTAL_MISTAKES_FAIL: `GET_TOTAL_MISTAKES_FAIL`,
};
